### ISSUE TITLE
Mod seems to be breaking creative flight

### ISSUE THREAD

**Issue by Saereth** [STS15/Fargos-Talismans#1] opened 2024-08-21 02:06 UTC
Basiscally when the mod is installed all forms of creative flight seem to stutter and make you fall. I'm providing a little video so you can see first hand.

This is on MC 1.21.1
Neoforge: 21.1.22
fargostalismans-2.0.4

https://drive.google.com/file/d/1yH7qcmhBh25_JQRj_s7JHCbqv1oteeYy/view?usp=sharing

Removing the mod causes this issue to go away

**Comment by STS15** [comment] 2024-08-21 03:26
Great video, was very helpful in figuring out the issue.  It stemmed from the event handler in the soul of flight mastery class.  It was checking if the player has the soul equipped, and if not to toggle the NeoForgeMod.CREATIVE_FLIGHT attribute to 0 which disables creative flight.  I was unable to reproduce in singleplayer but was able to replicate in multiplayer.  I added a check in that the player is not in creative or spectator modes so this should no longer attempt to toggle on the player unexpectedly.  Fixed in 2.0.5

**Closed by STS15** 2024-08-21 03:26 UTC
Labels: bug
